"""empty message

Revision ID: 161521943d05
Revises: 3de6814c4ae9
Create Date: 2021-02-03 16:29:11.686216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161521943d05'
down_revision = '3de6814c4ae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    # ### end Alembic commands ###
