"""empty message

Revision ID: 3f3d84eae10b
Revises: d27de90eeb59
Create Date: 2021-02-04 19:55:24.885491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f3d84eae10b'
down_revision = 'd27de90eeb59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('instagram', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('pinterest', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('twitter', sa.String(), nullable=False))
        batch_op.drop_column('link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('twitter')
        batch_op.drop_column('pinterest')
        batch_op.drop_column('instagram')
        batch_op.drop_column('facebook')

    # ### end Alembic commands ###
