"""empty message

Revision ID: 8cdd273fff65
Revises: 6db4a2e3cbf5
Create Date: 2021-02-07 15:42:46.420945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cdd273fff65'
down_revision = '6db4a2e3cbf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about', schema=None) as batch_op:
        batch_op.alter_column('detail',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about', schema=None) as batch_op:
        batch_op.alter_column('detail',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
