"""empty message

Revision ID: 95ceee4213c2
Revises: ae0cf6016166
Create Date: 2021-02-05 23:38:22.810931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95ceee4213c2'
down_revision = 'ae0cf6016166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoryName', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.drop_column('categoryName')

    # ### end Alembic commands ###
