"""empty message

Revision ID: d71c540bd171
Revises: a0d74a375dd4
Create Date: 2021-01-19 22:33:15.181641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd71c540bd171'
down_revision = 'a0d74a375dd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('blogdetail', sa.String(), nullable=True))
    op.add_column('blog', sa.Column('blogimg', sa.String(), nullable=True))
    op.add_column('blog', sa.Column('blogtitle', sa.String(), nullable=True))
    op.drop_column('blog', 'img')
    op.drop_column('blog', 'title')
    op.drop_column('blog', 'detail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('detail', sa.VARCHAR(), nullable=True))
    op.add_column('blog', sa.Column('title', sa.VARCHAR(), nullable=True))
    op.add_column('blog', sa.Column('img', sa.VARCHAR(), nullable=True))
    op.drop_column('blog', 'blogtitle')
    op.drop_column('blog', 'blogimg')
    op.drop_column('blog', 'blogdetail')
    # ### end Alembic commands ###
